-- WORLDOFTOYS seed data
-- Generated from src/components/partials/Home/Home.config.ts and other mock/static data.

BEGIN;

TRUNCATE TABLE
  cart_items,
  wishlist_items,
  order_items,
  orders,
  customer_profiles,
  users,
  translations,
  collection_categories,
  collections,
  brands,
  brand_features,
  age_filters,
  hero_banners,
  products,
  categories
RESTART IDENTITY CASCADE;

INSERT INTO categories (id, label, slug, icon) VALUES
  ('1', 'Plush Toys', 'plush-toys', 'heart'),
  ('2', 'Wooden Toys', 'wooden-toys', 'box'),
  ('3', 'Baby Toys', 'baby-toys', 'star'),
  ('4', 'Musical', 'musical', 'music'),
  ('5', 'Arts & Crafts', 'arts-crafts', 'paint'),
  ('6', 'Dress Up', 'dress-up', 'shirt'),
  ('7', 'Vehicles', 'vehicles', 'radio'),
  ('8', 'Board Games', 'board-games', 'grid'),
  ('9', 'Outdoor', 'outdoor', 'sun'),
  ('10', 'Puzzles', 'puzzles', 'puzzle'),
  ('11', 'Building Blocks', 'building-blocks', 'box'),
  ('12', 'STEM & Science', 'stem-science', 'flask'),
  ('13', 'Remote Control', 'remote-control', 'radio'),
  ('14', 'Action Figures', 'action-figures', 'shield'),
  ('15', 'Dolls', 'dolls', 'star');

INSERT INTO products (id, name, price, original_price, image_url, category_id, badge, rating, review_count, in_stock, age_group) VALUES
  ('p1', 'Soft Rainbow Stacking Rings', 12.99, NULL, 'https://www.junioredition.com/cdn/shop/products/PlanToys_SS18_Rainbow_Stacking_Rings_Toy.jpg?v=1542031634&width=1200', '3', 'popular', 4.9, 1842, TRUE, '0-2'),
  ('p2', 'Baby Plush Teddy Bear 30cm', 19.99, NULL, 'https://lovelybears.com.au/cdn/shop/files/Clove30cm_1024x1024.jpg?v=1704684649', '1', 'popular', 4.8, 2310, TRUE, '0-2'),
  ('p3', 'Squeeze & Float Bath Toy Set', 14.99, 19.99, 'https://p16-oec-va.ibyteimg.com/tos-maliva-i-o3syd03w52-us/6d1d2f3569af4f4ab1cb52ee3b044591~tplv-o3syd03w52-crop-webp:1200:1200.webp?dr=15592&t=555f072d&ps=933b5bde&shp=8dbd94bf&shcp=e1be8f53&idc=my2&from=2378011839', '3', 'sale', 4.7, 983, TRUE, '0-2'),
  ('p4', 'Baby Activity Gym & Play Mat', 39.99, NULL, 'https://infantino.com/cdn/shop/products/216-339_P1_1_grande.jpg?v=1532027252', '3', 'new', 4.8, 547, TRUE, '0-2'),
  ('p5', 'Musical Crib Mobile Stars', 29.99, NULL, 'https://cdn02.pinkoi.com/product/aaDcPPMC/0/1/640x530.jpg', '4', 'new', 4.6, 412, TRUE, '0-2'),
  ('p6', 'Wooden Shape Sorter Box', 24.99, NULL, 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=400&q=80&fit=crop', '2', NULL, 4.7, 728, TRUE, '0-2'),
  ('p7', 'Soft Fabric Sensory Activity Book', 9.99, NULL, 'https://m.media-amazon.com/images/I/61swbNPdtxL._AC_UF894,1000_QL80_DpWeblab_.jpg', '3', NULL, 4.5, 654, TRUE, '0-2'),
  ('p8', 'Baby Sensory Crinkle Rattle Set', 11.99, 16.99, 'https://i.ebayimg.com/images/g/R-UAAeSwBvJpcIH3/s-l400.jpg', '3', 'sale', 4.6, 331, TRUE, '0-2'),
  ('p9', 'Giraffe Rattle & Teether Toy', 8.99, NULL, 'https://m.media-amazon.com/images/I/719qxclGLtL._AC_UF894,1000_QL80_.jpg', '3', NULL, 4.7, 1104, TRUE, '0-2'),
  ('p10', 'Classic Pull-Along Wooden Duck', 16.99, NULL, 'https://babygifts.ie/cdn/shop/products/Classic-World-Pull-Along-Ducks1_600x.jpg?v=1632873579', '2', 'popular', 4.8, 877, TRUE, '0-2'),
  ('p11', 'Baby Piano Play Mat Musical', 34.99, 44.99, 'https://m.media-amazon.com/images/I/71mLqJaFcNL.jpg', '4', 'sale', 4.7, 623, TRUE, '0-2'),
  ('p12', 'Soft Silicone Stacking Cups 6pcs', 7.99, NULL, 'https://i.ebayimg.com/images/g/6aQAAOSwsAJifPeR/s-l400.jpg', '3', NULL, 4.5, 289, TRUE, '0-2'),
  ('p13', 'Deluxe Play Kitchen Set', 79.99, 99.99, 'https://www.abcthebaby.com/wp-content/uploads/2023/05/E3177A-Deluxe-Kitchen-Playset-with-Fan-Fryer.jpg', '15', 'sale', 4.8, 1253, TRUE, '3-5'),
  ('p14', 'Washable Finger Paint Set 12 Colors', 14.99, NULL, 'https://i5.walmartimages.com/seo/12-Color-Washable-Finger-Paint-Set-Kids-Funny-Fingers-Painting-Art-Drawing-Supplies-for-Painting-DIY-Crafts-Gifts-Early-Learning_c23b9d75-0b47-49fa-b9d7-cc49cfdf4a98.68dca311dbbdc4cc527d5e8722be8d1e.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF', '5', NULL, 4.6, 892, TRUE, '3-5'),
  ('p15', 'Princess Fairy Dress-Up Kit', 24.99, NULL, 'https://m.media-amazon.com/images/I/61lVD3WvR2L._AC_UY1100_.jpg', '6', 'popular', 4.7, 1045, TRUE, '3-5'),
  ('p16', 'Wooden Train Track Set 40pcs', 44.99, NULL, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDzCbjR2JQQvGQ161Zu5h8zwKT1ETNLez5RA&s', '2', 'popular', 4.9, 2087, TRUE, '3-5'),
  ('p17', 'Memory Matching Card Game', 12.99, NULL, 'https://m.media-amazon.com/images/I/81tfbZExDbL._AC_UF894,1000_QL80_.jpg', '8', NULL, 4.5, 743, TRUE, '3-5'),
  ('p18', 'Kids Art & Craft Activity Box', 29.99, 39.99, 'https://mycreativebox.com/cdn/shop/files/product_1_1200x.png?v=1779150764', '5', 'sale', 4.7, 631, TRUE, '3-5'),
  ('p19', '24-Piece Foam Floor Puzzle Animals', 17.99, NULL, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfxOxjO9Y-NhLgI6vidrzScF9_Atl6kxOfEw&s', '10', 'new', 4.6, 418, TRUE, '3-5'),
  ('p20', 'Sand & Water Outdoor Play Table', 54.99, 69.99, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUZfahrEEZJtQr5qLR1AcpetchoXBfA0CPcA&s', '9', 'sale', 4.8, 912, TRUE, '3-5'),
  ('p21', 'Jumbo Bubble Gun & Solution Set', 9.99, NULL, 'https://www.toysrus.co.th/dw/image/v2/BDGJ_PRD/on/demandware.static/-/Sites-master-catalog-toysrus/default/dw6ef91680/9/9/1/3/9913c0fd44c28d0d0eba107b5665a67ac93bb637_936761_i1.jpg?sw=394&sh=394&q=75', '9', NULL, 4.4, 567, TRUE, '3-5'),
  ('p22', 'Multi-Level Toy Vehicle Garage', 39.99, NULL, 'https://mentari.toys/cdn/shop/products/multi-level-garage-with-lift-mt7912-866972.jpg?v=1710167545', '7', 'popular', 4.7, 784, TRUE, '3-5'),
  ('p23', 'Doctor & Nurse Role-Play Kit', 19.99, NULL, 'https://m.media-amazon.com/images/I/91DPROnI1bL._AC_UF894,1000_QL80_.jpg', '15', NULL, 4.5, 489, TRUE, '3-5'),
  ('p24', 'Dinosaur World Figurine 12-Pack', 22.99, NULL, 'https://i5.walmartimages.com/seo/Pack-of-12-Ja-Ru-Dino-World-Dinosaurs-1-ea_bff9e38e-7db8-4cf6-87de-b27048bad902.45a1eccf0ff7ded68917616ebe06fa10.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF', '14', 'popular', 4.8, 1563, TRUE, '3-5'),
  ('p25', 'Classic Farm Animals Playset', 34.99, NULL, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWAkunudNJCyIOiwO_j00_axs_rE9TSEF_pA&s', '15', NULL, 4.6, 349, TRUE, '3-5'),
  ('p26', 'Kids Mini Drum Kit Set', 44.99, 59.99, 'https://i5.walmartimages.com/seo/Donner-Kids-Size-Drums-Sets-14-5-Piece-Complete-Drum-Kit-for-Child-Beginners-Percussion-Musical-Toy-Metallic-Blue_a4cf7b13-ac30-4566-be6d-e9dbb889a64a.4effa0564b3d41a0ee47ede406bd16be.jpeg', '4', 'sale', 4.7, 527, TRUE, '3-5'),
  ('p27', 'Store Cash Register', 27.99, NULL, 'https://m.media-amazon.com/images/I/811KsYDquwL.jpg', '15', NULL, 4.5, 398, TRUE, '3-5'),
  ('p28', 'LEGO Classic Creative Brick Box', 49.99, NULL, 'https://www.toysrus.co.th/dw/image/v2/BDGJ_PRD/on/demandware.static/-/Sites-master-catalog-toysrus/default/dw8bf469cc/3/6/8/7/3687efdb541a79457b9d1d42d939eb88a03cbe93_49110_i1.jpg?sw=500&sh=500&q=75', '11', 'popular', 4.9, 4821, TRUE, '6+'),
  ('p29', 'RC Turbo Racing Car Pro', 39.99, 59.99, 'https://shop.makerfire.com/cdn/shop/files/Turboracingsportscarred1.jpg?v=1741926475', '13', 'sale', 4.6, 1189, TRUE, '6+'),
  ('p30', 'Science Explorer Lab Kit Pro', 34.99, NULL, 'https://m.media-amazon.com/images/I/61kvAJIAPtL._AC_UF1000,1000_QL80_.jpg', '12', 'new', 4.7, 698, TRUE, '6+'),
  ('p31', 'Monopoly Junior Family Edition', 24.99, NULL, 'https://m.media-amazon.com/images/I/81DPZQ6tQYL.jpg', '8', NULL, 4.5, 2134, TRUE, '6+'),
  ('p32', '20-inch Adventure Mountain Bike', 129.99, 159.99, 'https://contents.mediadecathlon.com/p2642766/k$f1a421e42b5d2bddeb9d67824013203b/20-expl-500-orange-cnfr-btwin-8874418.jpg?f=768x0&format=auto', '9', 'sale', 4.7, 811, FALSE, '6+'),
  ('p33', 'Magnetic Tile Building Set 100pcs', 54.99, NULL, 'https://m.media-amazon.com/images/I/51Isiza6ghL._AC_US1000_.jpg', '11', 'new', 4.8, 943, TRUE, '6+'),
  ('p34', 'Premium Watercolor Art Studio Set', 27.99, NULL, 'https://ph-live-01.slatic.net/p/7e0424cf29cff6318594c458b1dbc7ec.jpg', '5', NULL, 4.6, 567, TRUE, '6+'),
  ('p35', 'RC Stunt Helicopter 2.4GHz', 44.99, NULL, 'https://m.media-amazon.com/images/I/51lX6Vc-KVL._AC_UF894,1000_QL80_.jpg', '13', 'new', 4.5, 432, TRUE, '6+'),
  ('p36', 'Long-Range Kids Walkie-Talkie Set', 19.99, 29.99, 'https://m.media-amazon.com/images/I/71GCacgNxNL.jpg', '13', 'sale', 4.4, 378, TRUE, '6+'),
  ('p37', 'Solar System Planetarium Kit', 39.99, NULL, 'https://m.media-amazon.com/images/I/81OXH1JBQpS._AC_UF894,1000_QL80_.jpg', '12', 'new', 4.8, 521, TRUE, '6+'),
  ('p38', 'Coding Robot for Kid', 69.99, NULL, 'https://down-th.img.susercontent.com/file/sg-11134201-7req2-m8snrpakt4lt3d', '12', 'new', 4.7, 287, TRUE, '6+'),
  ('p39', 'Table Tennis Ping-Pong Set', 34.99, NULL, 'https://i5.walmartimages.com/seo/PRO-SPIN-All-in-One-Portable-Ping-Pong-Set-with-Retractable-Net-High-Performance-Ping-Pong-Paddles-2-Player-Set-Indoor-Outdoor-Game_007c7c8f-df35-4a3f-b5a0-4a6d821921e7.4982b03cb6d7fd57db1e39d0dcbf1c5c.jpeg', '9', NULL, 4.5, 413, TRUE, '6+'),
  ('p40', '500-Piece Nature Jigsaw Puzzle', 21.99, NULL, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6wuKlULvqmG_q-qsNtOAcglmv09Qv_SOSrw&s', '10', NULL, 4.6, 889, TRUE, '6+'),
  ('p41', 'Crystal Growing Science Lab Kit', 18.99, 26.99, 'https://m.media-amazon.com/images/I/91v8uM8z-8L.jpg', '12', 'sale', 4.7, 634, TRUE, '6+'),
  ('p42', 'Classic Chess & Checkers Combo Set', 22.99, 34.99, 'https://www.gamesworld.com.au/wp-content/uploads/2025/11/6c877bd996c487022e1f5ecd68cff126c45640ca.jpg', '8', 'sale', 4.8, 1122, TRUE, '6+');

INSERT INTO hero_banners (id, title, subtitle, cta, cta_link, gradient, image_url, display_order) VALUES
  ('1', 'Summer Play Collection', 'Outdoor toys and water games for endless summer fun', 'Shop Outdoor', '/outdoor', 'linear-gradient(135deg, #1565C0 0%, #AA00FF 100%)', 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&q=80&fit=crop', 1),
  ('2', 'New Arrivals Just In', 'The hottest toys of the season — be the first to get them', 'View All Deals', '/deals', 'linear-gradient(135deg, #FF1744 0%, #FF6D00 100%)', 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800&q=80&fit=crop', 2);

INSERT INTO age_filters (id, label, value, display_order) VALUES
  ('age-all', 'All Ages', 'all', 1),
  ('age-0-2', '0-2 years', '0-2', 2),
  ('age-3-5', '3-5 years', '3-5', 3),
  ('age-6plus', '6-8+ years', '6+', 4);

INSERT INTO brand_features (id, title, description, icon, color, display_order) VALUES
  ('feature-1', 'Free Shipping', 'On all orders over $50', 'truck', 'blue', 1),
  ('feature-2', 'Easy Returns', '30-day hassle-free returns', 'refresh', 'green', 2),
  ('feature-3', 'Secure Payment', '100% safe transactions', 'lock', 'purple', 3),
  ('feature-4', '24/7 Support', 'Dedicated customer service', 'headphones', 'orange', 4);

INSERT INTO brands (id, name, category_id, description, product_count, color_class, tag_color_class, display_order) VALUES
  ('lego', 'LEGO', '11', 'Creative building sets for all ages', 2, 'bg-yellow-400', 'text-yellow-800 bg-yellow-100', 1),
  ('mattel', 'Mattel', '15', 'Iconic toys including Barbie & Hot Wheels', 3, 'bg-red-500', 'text-red-800 bg-red-100', 2),
  ('hasbro', 'Hasbro', '8', 'Board games, puzzles & action figures', 4, 'bg-blue-500', 'text-blue-800 bg-blue-100', 3),
  ('fisher-price', 'Fisher-Price', '3', 'Safe learning toys for babies & toddlers', 6, 'bg-orange-400', 'text-orange-800 bg-orange-100', 4),
  ('vtech', 'VTech', '3', 'Electronic learning toys for kids', 3, 'bg-green-500', 'text-green-800 bg-green-100', 5),
  ('playmobil', 'Playmobil', '14', 'Creative playsets for imaginative play', 2, 'bg-purple-500', 'text-purple-800 bg-purple-100', 6),
  ('melissa-doug', 'Melissa & Doug', '2', 'Wooden toys & arts and crafts', 4, 'bg-teal-500', 'text-teal-800 bg-teal-100', 7),
  ('play-doh', 'Play-Doh', '5', 'Classic modeling compound & creative sets', 2, 'bg-pink-400', 'text-pink-800 bg-pink-100', 8),
  ('hot-wheels', 'Hot Wheels', '7', 'Die-cast cars & racing tracks', 2, 'bg-red-600', 'text-red-800 bg-red-100', 9),
  ('nerf', 'Nerf', '9', 'Foam blasters & outdoor action', 2, 'bg-orange-500', 'text-orange-800 bg-orange-100', 10),
  ('barbie', 'Barbie', '15', 'Fashion dolls & playsets for girls', 2, 'bg-pink-500', 'text-pink-800 bg-pink-100', 11),
  ('bruder', 'Bruder', '7', 'Realistic toy vehicles & construction', 2, 'bg-yellow-500', 'text-yellow-800 bg-yellow-100', 12);

INSERT INTO collections (id, title, slug, description, rule_type, rule_value, gradient) VALUES
  ('deals', 'Today''s Best Deals', 'deals', 'Products whose badge is sale.', 'badge', 'sale', 'linear-gradient(135deg, #FF1744 0%, #FF6D00 100%)'),
  ('outdoor', 'Outdoor Collection', 'outdoor', 'Outdoor and remote control products.', 'category', NULL, 'linear-gradient(135deg, #00C853 0%, #1565C0 100%)'),
  ('learning', 'Learning & Creativity', 'learning', 'STEM, arts, music, and wooden toys.', 'category', NULL, 'linear-gradient(135deg, #00C853 0%, #1565C0 100%)'),
  ('games', 'Games', 'games', 'Board games and puzzles.', 'category', NULL, 'linear-gradient(135deg, #7B1FA2 0%, #1565C0 100%)');

INSERT INTO collection_categories (collection_id, category_id) VALUES
  ('outdoor', '9'),
  ('outdoor', '13'),
  ('learning', '12'),
  ('learning', '5'),
  ('learning', '4'),
  ('learning', '2'),
  ('games', '8'),
  ('games', '10');

INSERT INTO translations (language, key, value) VALUES
  ('en', 'navToys', 'Toys'),
  ('en', 'navGames', 'Games'),
  ('en', 'navOutdoor', 'Outdoor'),
  ('en', 'navLearning', 'Learning'),
  ('en', 'navDeals', 'Deals'),
  ('en', 'navBrands', 'Brands'),
  ('en', 'navAccount', 'Account'),
  ('en', 'navWishlist', 'Wishlist'),
  ('en', 'navCart', 'Cart'),
  ('en', 'navSignIn', 'Sign In'),
  ('en', 'navSignOut', 'Sign Out'),
  ('en', 'navMyAccount', 'My Account'),
  ('en', 'navSearch', 'Search for toys, games, brands...'),
  ('en', 'shopByCategory', 'Shop by Category'),
  ('en', 'viewAll', 'View all'),
  ('en', 'ourCollection', 'Our Collection'),
  ('en', 'allAges', 'All Ages'),
  ('en', 'age02', '0-2 years'),
  ('en', 'age35', '3-5 years'),
  ('en', 'age6Plus', '6-8+ years'),
  ('en', 'addToCart', 'Add to Cart'),
  ('en', 'unavailable', 'Unavailable'),
  ('en', 'viewAllDeals', 'View All Deals'),
  ('en', 'outOfStock', 'Out of Stock'),
  ('en', 'productsAvailable', 'products available'),
  ('en', 'freeShippingBanner', 'Free shipping on orders over $50 — Shop the latest arrivals now'),
  ('en', 'freeShipping', 'Free Shipping'),
  ('en', 'freeShippingDesc', 'On all orders over $50'),
  ('en', 'easyReturns', 'Easy Returns'),
  ('en', 'easyReturnsDesc', '30-day hassle-free returns'),
  ('en', 'securePayment', 'Secure Payment'),
  ('en', 'securePaymentDesc', '100% safe transactions'),
  ('en', 'support', '24/7 Support'),
  ('en', 'supportDesc', 'Dedicated customer service'),
  ('en', 'loginTab', 'login'),
  ('en', 'registerTab', 'register'),
  ('en', 'loginWith', 'login with...'),
  ('en', 'loginSociallyDesc', 'login socially for a faster checkout'),
  ('en', 'loginToAccount', 'login to my account'),
  ('en', 'emailLabel', 'login'),
  ('en', 'emailPlaceholder', 'email address'),
  ('en', 'loginWithMobile', 'login with mobile'),
  ('en', 'passwordLabel', 'password'),
  ('en', 'passwordPlaceholder', 'password'),
  ('en', 'rememberMe', 'remember me'),
  ('en', 'forgotPassword', 'forgot password?'),
  ('en', 'loginBtn', 'login'),
  ('en', 'or', 'or'),
  ('en', 'continueAsGuest', 'Continue as Guest'),
  ('en', 'guestNote', 'You will not be able to track your order as a guest'),
  ('en', 'firstNameLabel', 'First Name'),
  ('en', 'lastNameLabel', 'Last Name'),
  ('en', 'confirmPasswordLabel', 'Confirm Password'),
  ('en', 'confirmPasswordPlaceholder', 'Re-enter password'),
  ('en', 'newsletterLabel', 'Subscribe to our newsletter for exclusive deals and new arrivals'),
  ('en', 'createAccountBtn', 'Create Account'),
  ('en', 'alreadyHaveAccount', 'Already have an account?'),
  ('en', 'dontHaveAccount', 'Don''t have an account?'),
  ('en', 'signInRequired', 'Sign in required to place order'),
  ('en', 'signInRequiredDesc', 'You will be prompted to sign in or create an account at checkout.'),
  ('en', 'signedInAs', 'Signed in as'),
  ('en', 'stepSignIn', 'Sign In'),
  ('en', 'stepPayment', 'Payment'),
  ('en', 'stepConfirm', 'Confirm'),
  ('en', 'secureCheckout', 'Secure Checkout'),
  ('en', 'shoppingCart', 'Shopping Cart'),
  ('en', 'itemsLabel', 'items'),
  ('en', 'emptyCart', 'Your cart is empty'),
  ('en', 'emptyCartDesc', 'Add some toys to get started!'),
  ('en', 'browseProducts', 'Browse Products'),
  ('en', 'orderSummary', 'Order Summary'),
  ('en', 'subtotal', 'Subtotal'),
  ('en', 'shippingLabel', 'Shipping'),
  ('en', 'taxLabel', 'Tax (7%)'),
  ('en', 'total', 'Total'),
  ('en', 'freeLabel', 'FREE'),
  ('en', 'placeOrder', 'Place Order'),
  ('en', 'signInToOrder', 'Sign In to Place Order'),
  ('en', 'orderConfirmed', 'Order Confirmed!'),
  ('en', 'orderThankYou', 'Thank you! Your order is being processed.'),
  ('en', 'continueShopping', 'Continue Shopping'),
  ('en', 'paymentMethod', 'Payment Method'),
  ('en', 'shopByBrand', 'Shop by Brand'),
  ('en', 'noProducts', 'No products in this category yet.'),
  ('en', 'limitedTime', 'Limited Time'),
  ('en', 'newSeason', 'New Season'),
  ('en', 'shopGames', 'Shop Games'),
  ('en', 'shopOutdoor', 'Shop Outdoor'),
  ('en', 'newsletterHeading', 'Get exclusive deals and new arrivals'),
  ('en', 'newsletterSub', 'Subscribe to our newsletter and save 10% on your first order.'),
  ('en', 'subscribeBtn', 'Subscribe'),
  ('th', 'navToys', 'ของเล่น'),
  ('th', 'navGames', 'เกม'),
  ('th', 'navOutdoor', 'กลางแจ้ง'),
  ('th', 'navLearning', 'การเรียนรู้'),
  ('th', 'navDeals', 'โปรโมชั่น'),
  ('th', 'navBrands', 'แบรนด์'),
  ('th', 'navAccount', 'บัญชี'),
  ('th', 'navWishlist', 'รายการโปรด'),
  ('th', 'navCart', 'ตะกร้า'),
  ('th', 'navSignIn', 'เข้าสู่ระบบ'),
  ('th', 'navSignOut', 'ออกจากระบบ'),
  ('th', 'navMyAccount', 'บัญชีของฉัน'),
  ('th', 'navSearch', 'ค้นหาของเล่น เกม แบรนด์...'),
  ('th', 'shopByCategory', 'ช้อปตามหมวดหมู่'),
  ('th', 'viewAll', 'ดูทั้งหมด'),
  ('th', 'ourCollection', 'คอลเลกชันของเรา'),
  ('th', 'allAges', 'ทุกช่วงวัย'),
  ('th', 'age02', '0-2 ปี'),
  ('th', 'age35', '3-5 ปี'),
  ('th', 'age6Plus', '6 ปีขึ้นไป'),
  ('th', 'addToCart', 'เพิ่มในตะกร้า'),
  ('th', 'unavailable', 'ไม่พร้อมจำหน่าย'),
  ('th', 'viewAllDeals', 'ดูโปรโมชั่นทั้งหมด'),
  ('th', 'outOfStock', 'สินค้าหมด'),
  ('th', 'productsAvailable', 'สินค้าในหมวดหมู่นี้'),
  ('th', 'freeShippingBanner', 'ส่งฟรีเมื่อซื้อครบ $50 — ช้อปสินค้าใหม่ล่าสุดได้เลย'),
  ('th', 'freeShipping', 'จัดส่งฟรี'),
  ('th', 'freeShippingDesc', 'สำหรับคำสั่งซื้อเกิน $50'),
  ('th', 'easyReturns', 'คืนสินค้าง่าย'),
  ('th', 'easyReturnsDesc', 'คืนได้ภายใน 30 วัน'),
  ('th', 'securePayment', 'ชำระเงินปลอดภัย'),
  ('th', 'securePaymentDesc', 'ธุรกรรมปลอดภัย 100%'),
  ('th', 'support', 'บริการ 24/7'),
  ('th', 'supportDesc', 'ทีมบริการพร้อมช่วยเหลือ'),
  ('th', 'loginTab', 'เข้าสู่ระบบ'),
  ('th', 'registerTab', 'สมัครสมาชิก'),
  ('th', 'loginWith', 'เข้าสู่ระบบด้วย...'),
  ('th', 'loginSociallyDesc', 'เข้าสู่ระบบผ่านโซเชียลเพื่อชำระเงินเร็วขึ้น'),
  ('th', 'loginToAccount', 'เข้าสู่ระบบด้วยอีเมล'),
  ('th', 'emailLabel', 'อีเมล'),
  ('th', 'emailPlaceholder', 'ที่อยู่อีเมล'),
  ('th', 'loginWithMobile', 'เข้าสู่ระบบด้วยเบอร์โทร'),
  ('th', 'passwordLabel', 'รหัสผ่าน'),
  ('th', 'passwordPlaceholder', 'รหัสผ่าน'),
  ('th', 'rememberMe', 'จดจำฉัน'),
  ('th', 'forgotPassword', 'ลืมรหัสผ่าน?'),
  ('th', 'loginBtn', 'เข้าสู่ระบบ'),
  ('th', 'or', 'หรือ'),
  ('th', 'continueAsGuest', 'ดำเนินการในฐานะผู้เยี่ยมชม'),
  ('th', 'guestNote', 'คุณจะไม่สามารถติดตามคำสั่งซื้อในฐานะผู้เยี่ยมชม'),
  ('th', 'firstNameLabel', 'ชื่อ'),
  ('th', 'lastNameLabel', 'นามสกุล'),
  ('th', 'confirmPasswordLabel', 'ยืนยันรหัสผ่าน'),
  ('th', 'confirmPasswordPlaceholder', 'กรอกรหัสผ่านอีกครั้ง'),
  ('th', 'newsletterLabel', 'รับข่าวสารโปรโมชั่นและสินค้าใหม่'),
  ('th', 'createAccountBtn', 'สร้างบัญชี'),
  ('th', 'alreadyHaveAccount', 'มีบัญชีแล้ว?'),
  ('th', 'dontHaveAccount', 'ยังไม่มีบัญชี?'),
  ('th', 'signInRequired', 'ต้องเข้าสู่ระบบเพื่อสั่งซื้อ'),
  ('th', 'signInRequiredDesc', 'คุณจะถูกขอให้เข้าสู่ระบบหรือสร้างบัญชีในขั้นตอนชำระเงิน'),
  ('th', 'signedInAs', 'เข้าสู่ระบบในชื่อ'),
  ('th', 'stepSignIn', 'เข้าสู่ระบบ'),
  ('th', 'stepPayment', 'ชำระเงิน'),
  ('th', 'stepConfirm', 'ยืนยัน'),
  ('th', 'secureCheckout', 'ชำระเงินปลอดภัย'),
  ('th', 'shoppingCart', 'ตะกร้าสินค้า'),
  ('th', 'itemsLabel', 'รายการ'),
  ('th', 'emptyCart', 'ตะกร้าของคุณว่างเปล่า'),
  ('th', 'emptyCartDesc', 'เพิ่มของเล่นในตะกร้าเพื่อเริ่มต้น!'),
  ('th', 'browseProducts', 'ดูสินค้า'),
  ('th', 'orderSummary', 'สรุปคำสั่งซื้อ'),
  ('th', 'subtotal', 'ยอดรวมสินค้า'),
  ('th', 'shippingLabel', 'ค่าจัดส่ง'),
  ('th', 'taxLabel', 'ภาษี (7%)'),
  ('th', 'total', 'รวมทั้งหมด'),
  ('th', 'freeLabel', 'ฟรี'),
  ('th', 'placeOrder', 'สั่งซื้อ'),
  ('th', 'signInToOrder', 'เข้าสู่ระบบเพื่อสั่งซื้อ'),
  ('th', 'orderConfirmed', 'ยืนยันคำสั่งซื้อแล้ว!'),
  ('th', 'orderThankYou', 'ขอบคุณ! คำสั่งซื้อของคุณกำลังดำเนินการ'),
  ('th', 'continueShopping', 'ช้อปต่อ'),
  ('th', 'paymentMethod', 'วิธีการชำระเงิน'),
  ('th', 'shopByBrand', 'ช้อปตามแบรนด์'),
  ('th', 'noProducts', 'ยังไม่มีสินค้าในหมวดหมู่นี้'),
  ('th', 'limitedTime', 'เวลาจำกัด'),
  ('th', 'newSeason', 'ฤดูกาลใหม่'),
  ('th', 'shopGames', 'ช้อปเกม'),
  ('th', 'shopOutdoor', 'ช้อปของเล่นกลางแจ้ง'),
  ('th', 'newsletterHeading', 'รับดีลพิเศษและสินค้าใหม่'),
  ('th', 'newsletterSub', 'สมัครรับจดหมายข่าวและรับส่วนลด 10% สำหรับคำสั่งซื้อแรก'),
  ('th', 'subscribeBtn', 'สมัคร'),
  ('zh', 'navToys', '玩具'),
  ('zh', 'navGames', '游戏'),
  ('zh', 'navOutdoor', '户外'),
  ('zh', 'navLearning', '学习教育'),
  ('zh', 'navDeals', '优惠活动'),
  ('zh', 'navBrands', '品牌'),
  ('zh', 'navAccount', '账户'),
  ('zh', 'navWishlist', '收藏夹'),
  ('zh', 'navCart', '购物车'),
  ('zh', 'navSignIn', '登录'),
  ('zh', 'navSignOut', '退出登录'),
  ('zh', 'navMyAccount', '我的账户'),
  ('zh', 'navSearch', '搜索玩具、游戏、品牌...'),
  ('zh', 'shopByCategory', '按类别购物'),
  ('zh', 'viewAll', '查看全部'),
  ('zh', 'ourCollection', '精选商品'),
  ('zh', 'allAges', '所有年龄'),
  ('zh', 'age02', '0-2岁'),
  ('zh', 'age35', '3-5岁'),
  ('zh', 'age6Plus', '6岁以上'),
  ('zh', 'addToCart', '加入购物车'),
  ('zh', 'unavailable', '暂无货'),
  ('zh', 'viewAllDeals', '查看全部优惠'),
  ('zh', 'outOfStock', '缺货'),
  ('zh', 'productsAvailable', '件商品'),
  ('zh', 'freeShippingBanner', '订单满$50免运费 — 立即购买最新商品'),
  ('zh', 'freeShipping', '免费配送'),
  ('zh', 'freeShippingDesc', '订单满$50免运费'),
  ('zh', 'easyReturns', '轻松退货'),
  ('zh', 'easyReturnsDesc', '30天无忧退货'),
  ('zh', 'securePayment', '安全支付'),
  ('zh', 'securePaymentDesc', '100%安全交易'),
  ('zh', 'support', '全天候服务'),
  ('zh', 'supportDesc', '专属客户服务团队'),
  ('zh', 'loginTab', '登录'),
  ('zh', 'registerTab', '注册'),
  ('zh', 'loginWith', '使用以下方式登录...'),
  ('zh', 'loginSociallyDesc', '通过社交账号快速结账'),
  ('zh', 'loginToAccount', '使用账号登录'),
  ('zh', 'emailLabel', '登录'),
  ('zh', 'emailPlaceholder', '邮箱地址'),
  ('zh', 'loginWithMobile', '手机号登录'),
  ('zh', 'passwordLabel', '密码'),
  ('zh', 'passwordPlaceholder', '请输入密码'),
  ('zh', 'rememberMe', '记住我'),
  ('zh', 'forgotPassword', '忘记密码？'),
  ('zh', 'loginBtn', '登录'),
  ('zh', 'or', '或'),
  ('zh', 'continueAsGuest', '以游客身份继续'),
  ('zh', 'guestNote', '以游客身份无法追踪订单'),
  ('zh', 'firstNameLabel', '名'),
  ('zh', 'lastNameLabel', '姓'),
  ('zh', 'confirmPasswordLabel', '确认密码'),
  ('zh', 'confirmPasswordPlaceholder', '再次输入密码'),
  ('zh', 'newsletterLabel', '订阅通讯，获取专属优惠和新品信息'),
  ('zh', 'createAccountBtn', '创建账户'),
  ('zh', 'alreadyHaveAccount', '已有账户？'),
  ('zh', 'dontHaveAccount', '没有账户？'),
  ('zh', 'signInRequired', '下单前请先登录'),
  ('zh', 'signInRequiredDesc', '结账时将提示您登录或创建账户'),
  ('zh', 'signedInAs', '已登录为'),
  ('zh', 'stepSignIn', '登录'),
  ('zh', 'stepPayment', '支付'),
  ('zh', 'stepConfirm', '确认'),
  ('zh', 'secureCheckout', '安全结账'),
  ('zh', 'shoppingCart', '购物车'),
  ('zh', 'itemsLabel', '件商品'),
  ('zh', 'emptyCart', '购物车是空的'),
  ('zh', 'emptyCartDesc', '快去挑选您喜欢的玩具吧！'),
  ('zh', 'browseProducts', '浏览商品'),
  ('zh', 'orderSummary', '订单摘要'),
  ('zh', 'subtotal', '小计'),
  ('zh', 'shippingLabel', '运费'),
  ('zh', 'taxLabel', '税费 (7%)'),
  ('zh', 'total', '总计'),
  ('zh', 'freeLabel', '免费'),
  ('zh', 'placeOrder', '提交订单'),
  ('zh', 'signInToOrder', '登录后下单'),
  ('zh', 'orderConfirmed', '订单已确认！'),
  ('zh', 'orderThankYou', '感谢您的购买！您的订单正在处理中。'),
  ('zh', 'continueShopping', '继续购物'),
  ('zh', 'paymentMethod', '支付方式'),
  ('zh', 'shopByBrand', '按品牌购物'),
  ('zh', 'noProducts', '该分类暂无商品'),
  ('zh', 'limitedTime', '限时优惠'),
  ('zh', 'newSeason', '新季上市'),
  ('zh', 'shopGames', '购买游戏'),
  ('zh', 'shopOutdoor', '购买户外玩具'),
  ('zh', 'newsletterHeading', '获取专属优惠和新品资讯'),
  ('zh', 'newsletterSub', '订阅通讯，首单立享九折优惠'),
  ('zh', 'subscribeBtn', '订阅');

INSERT INTO users (id, first_name, last_name, email, provider, is_guest) VALUES
  ('user-alex-johnson', 'Alex', 'Johnson', 'alex.johnson@worldoftoys.com', 'email', FALSE),
  ('user-facebook', 'Facebook', 'User', 'user@facebook.com', 'facebook', FALSE),
  ('user-google', 'Google', 'User', 'user@gmail.com', 'google', FALSE),
  ('user-line', 'LINE', 'User', 'user@line.me', 'line', FALSE),
  ('user-guest', 'Guest', '', NULL, 'guest', TRUE);

INSERT INTO customer_profiles (user_id, phone, avatar_url, member_since, loyalty_points, address, tier) VALUES
  ('user-alex-johnson', '+1 (555) 234-5678', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80&fit=crop&crop=faces', '2023-03-01', 2450, '123 Maple Street, Los Angeles, CA 90001', 'Gold Member');

INSERT INTO orders (id, user_id, order_date, total, status, status_color_class) VALUES
  ('WOT-20241201', 'user-alex-johnson', '2024-12-01', 89.97, 'Delivered', 'text-green-600 bg-green-50'),
  ('WOT-20241115', 'user-alex-johnson', '2024-11-15', 44.99, 'Delivered', 'text-green-600 bg-green-50'),
  ('WOT-20241003', 'user-alex-johnson', '2024-10-03', 129.99, 'Delivered', 'text-green-600 bg-green-50'),
  ('WOT-20240918', 'user-alex-johnson', '2024-09-18', 67.50, 'Delivered', 'text-green-600 bg-green-50');

INSERT INTO order_items (id, order_id, product_id, product_name, quantity, unit_price) VALUES
  ('WOT-20241201-1', 'WOT-20241201', 'p28', 'LEGO Classic Creative Brick Box', 1, 49.99),
  ('WOT-20241201-2', 'WOT-20241201', 'p17', 'Memory Matching Card Game', 1, 12.99),
  ('WOT-20241115-1', 'WOT-20241115', 'p29', 'RC Turbo Racing Car Pro', 1, 39.99),
  ('WOT-20241003-1', 'WOT-20241003', 'p32', '20-inch Adventure Mountain Bike', 1, 129.99),
  ('WOT-20241003-2', 'WOT-20241003', NULL, 'Magnetic Tile Building Set', 1, NULL),
  ('WOT-20240918-1', 'WOT-20240918', 'p30', 'Science Explorer Lab Kit Pro', 1, 34.99),
  ('WOT-20240918-2', 'WOT-20240918', NULL, 'Crystal Growing Kit', 1, NULL),
  ('WOT-20240918-3', 'WOT-20240918', NULL, 'Puzzle 500pcs', 1, NULL);

COMMIT;
